---

- hosts: all
  tasks:
   - name: grab info
     runCmds:
     register: resultItem

   - name: first set
     set_fact:
       res={{resultItem.meta}}

   - debug: var=res

   - set_fact: my_token=0

   - name: just header
     local_action: spitResults name=header vals={{res}} token={{my_token}}
     register: my_token
     run_once: true

   - name: spit info
     local_action: spitResults name=spit vals={{res}} token={{my_token}}




