---

- hosts: all
  tasks:
   - name: grab info
     runCmds:
     register: resultItem

   - name: first set
     set_fact:
       res:'{{resultItem}}'

   - debug: var=res


   - name: add to dict list
     set_fact:
       resultList= "{{resultList| combine({item:resultItem})}}"
     with_items: dictItem

   - debug: var=resultList

   - name :  spit info
     spitResults: name=spit vals=resultList

