# This playbook consists of four plays. The first one pulls information about all the default rho facts and the second
# writes them to a csv with the name specified. The third one pulls information about only those facts we intend to
# collect (as demonstrated in the example) and the fourth one writes them to a file as specified.

---

- name: Collect all default facts
  hosts: all
  roles:
    - collect


- name: Write default facts first to a variable and then to csv locally
  hosts: localhost
  roles:
    - write







