---

- debug: var=hostvars[item]['res']
  with_items: "{{groups.alpha}}"
  tags:
    - default


- name: store facts from all hosts in a variable
  set_fact: host_fact={{hostvars[item]['res']}}
  with_items: "{{groups.alpha}}"
  register: host_facts

  tags:
    - default

- name: parse variable into a list of dictionaries
  set_fact: host_facts="{{ host_facts.results | map(attribute='ansible_facts.host_fact') | list }}"

  tags:
    - default

- name: write the list to a csv
  spitResults: name=spit file_path=report.csv vals={{host_facts}}

  tags:
    - default